apiVersion: storage.metalk8s.scality.com/v1alpha1
kind: Volume
metadata:
  name: %VOLUME_NAME%
spec:
  nodeName: %NODE_NAME%
  storageClassName: %STORAGE_CLASS_NAME%
  rawBlockDevice:
    devicePath: %DEVICE_PATH%
  template:
    metadata:
      labels:
        app: 'zenko'
